name: 'feed'
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 * * * *'

jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sarisia/actions-readme-feed@v1
        with:
          url: 'https://qiita.com/i4M1k0SU/feed'
          file: 'README.md'
          timezone: 'Asia/Tokyo'
      - uses: sarisia/actions-commit@master
        with:
          message: "docs: update feed"
 
